[generalize type] Internal Error with exception in catch clause

The following Java code is written under JDK 1.5.04 with the Java-Editor of Eclipse 3.1 (WinXP): ----------- <snip> ----------------- import java.io.*; public class C { public void f(File f) { try { FileInputStream is = new FileInputStream(f); } catch (FileNotFoundException ex) { System.err.println("file not found"); } } } -------------- </snip> --------------- When trying to generalize the type FileNotFoundException (refactoring), I get an "internal error during computation of valid types" (reproducable). When I do the same thing for the FileInputStream, everything is fine. Bye, Michael